# Site settings
title: 4980 Canine Crusaders
email: 4980robotics@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are a proud FIRST robotics team located in Kettle Falls, Washington. We are
   very lucky to have a supportive community who have helped us
  travel to St. Louis, Missouri last year for the Worlds competiton and to the Distric
  Championship the year before in Portland, Oregon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.4980robotics.com" # the base hostname & protocol for your site
twitter_username:  4980robotics
facebook_username: 4980 Canine Crusaders, Kettle Falls Robotics Team
youtube_username: FRC /#4980 Canine Crusaders

# Build settings
markdown: kramdown
